name: CI

on:
  push:
    branches:
    - master

jobs:
  lint:
    name: check linting issues
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: npm install
